extension_dir = "C:\Users\Hrishikesh Kali\AppData\Local\Microsoft\WinGet\Packages\PHP.PHP.8.3_Microsoft.WinGet.Source_8wekyb3d8bbwe\ext"
extension=mysqli
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
